
package by.training2019.autumn.webservices.soap.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.1
 * 
 */
@WebService(name = "Demo", targetNamespace = "http://ws.soap.webservices.autumn.training2019.by/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Demo {


    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "helloWorld", targetNamespace = "http://ws.soap.webservices.autumn.training2019.by/", className = "by.training2019.autumn.webservices.by.training2019.autumn.webservices.soap.client.HelloWorld")
    @ResponseWrapper(localName = "helloWorldResponse", targetNamespace = "http://ws.soap.webservices.autumn.training2019.by/", className = "by.training2019.autumn.webservices.by.training2019.autumn.webservices.soap.client.HelloWorldResponse")
    public String helloWorld();

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "sayHi", targetNamespace = "http://ws.soap.webservices.autumn.training2019.by/", className = "by.training2019.autumn.webservices.by.training2019.autumn.webservices.soap.client.SayHi")
    @ResponseWrapper(localName = "sayHiResponse", targetNamespace = "http://ws.soap.webservices.autumn.training2019.by/", className = "by.training2019.autumn.webservices.by.training2019.autumn.webservices.soap.client.SayHiResponse")
    public String sayHi(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
